-- MySQL Script generated by MySQL Workbench
-- Mon Jul 19 16:09:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FunCampApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FunCampApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FunCampApp` DEFAULT CHARACTER SET utf8 ;
USE `FunCampApp` ;

-- -----------------------------------------------------
-- Table `FunCampApp`.`DIRETTORE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`DIRETTORE` (
  `CF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Stipendio` DOUBLE NOT NULL,
  `AnniServ` INT NOT NULL,
  PRIMARY KEY (`CF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`TURNO LAVORO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`TURNO LAVORO` (
  `NumT` INT NOT NULL,
  `DataT` DATE NOT NULL,
  `OraI` TIME NOT NULL,
  `OraF` TIME NOT NULL,
  PRIMARY KEY (`NumT`, `DataT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`CONTRATTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`CONTRATTO` (
  `ID` INT NOT NULL,
  `Selettore` ENUM("aOre", "dipendente") NOT NULL,
  `Stipendio` DOUBLE NOT NULL,
  `AnniC` INT NULL,
  `Giorni` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`BENEFIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`BENEFIT` (
  `nOrdine` INT NOT NULL,
  `Descrizione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nOrdine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ATTRAZIONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ATTRAZIONE` (
  `Codice` INT NOT NULL,
  `LimiteEtà` INT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `OraA` TIME NOT NULL,
  `OraC` TIME NOT NULL,
  `NPostiDisponibili` INT NOT NULL,
  PRIMARY KEY (`Codice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`PACCHETTO OFFERTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`PACCHETTO OFFERTA` (
  `idP` INT NOT NULL,
  `dataVal` DATE NOT NULL,
  PRIMARY KEY (`idP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`TRANSAZIONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`TRANSAZIONE` (
  `codiceT` INT NOT NULL AUTO_INCREMENT,
  `importo` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`codiceT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`CLIENTE` (
  `numEntrata` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `età` INT NOT NULL,
  PRIMARY KEY (`numEntrata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ANIMALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ANIMALE` (
  `nome` VARCHAR(45) NOT NULL,
  `specie` VARCHAR(45) NOT NULL,
  `dieta` MULTILINESTRING NOT NULL,
  PRIMARY KEY (`nome`, `specie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`EVENTO SPECIALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`EVENTO SPECIALE` (
  `nome` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `OraF` TIME NOT NULL,
  `OraI` TIME NOT NULL,
  `Selettore` ENUM("conAnimali", "senzaAnimali") NOT NULL,
  PRIMARY KEY (`nome`, `data`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`STIPULAZIONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`STIPULAZIONE` (
  `CFDirettore` VARCHAR(45) NOT NULL,
  `IDContratto` INT NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `CFDirettore_idx` (`CFDirettore` ASC) VISIBLE,
  PRIMARY KEY (`CFDirettore`, `IDContratto`),
  CONSTRAINT `CFDirettore`
    FOREIGN KEY (`CFDirettore`)
    REFERENCES `FunCampApp`.`DIRETTORE` (`CF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDContratto`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`INCLUSIONEB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`INCLUSIONEB` (
  `IDContratto` INT NOT NULL,
  `nOrdine` INT NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `nOrdine_idx` (`nOrdine` ASC) VISIBLE,
  PRIMARY KEY (`IDContratto`, `nOrdine`),
  CONSTRAINT `IDC`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nOrdine`
    FOREIGN KEY (`nOrdine`)
    REFERENCES `FunCampApp`.`BENEFIT` (`nOrdine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`INSERVIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`INSERVIENTE` (
  `CodiceD` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `AnniServC` INT NOT NULL,
  PRIMARY KEY (`CodiceD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ADDETTO SICUREZZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ADDETTO SICUREZZA` (
  `CodiceD` INT NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `AnniServC` INT NOT NULL,
  PRIMARY KEY (`CodiceD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ADDETTO RECEPTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ADDETTO RECEPTION` (
  `CodiceD` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `AnniServC` INT NOT NULL,
  PRIMARY KEY (`CodiceD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ASSEGNAZIONE TR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ASSEGNAZIONE TR` (
  `CodiceDRec` INT NOT NULL,
  `nTurno` INT NOT NULL,
  `DTurno` DATE NOT NULL,
  INDEX `CodiceDRec_idx` (`CodiceDRec` ASC) INVISIBLE,
  PRIMARY KEY (`CodiceDRec`, `nTurno`, `DTurno`),
  INDEX `NTurno_idx` (`nTurno` ASC) VISIBLE,
  INDEX `DTurno_idx` (`DTurno` ASC) VISIBLE,
  CONSTRAINT `CodiceDRec`
    FOREIGN KEY (`CodiceDRec`)
    REFERENCES `FunCampApp`.`ADDETTO RECEPTION` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NTurno`
    FOREIGN KEY (`nTurno`)
    REFERENCES `FunCampApp`.`TURNO LAVORO` (`NumT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DTurno`
    FOREIGN KEY (`DTurno`)
    REFERENCES `FunCampApp`.`TURNO LAVORO` (`DataT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ASSEGNAZIONE TS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ASSEGNAZIONE TS` (
  `CodiceDSic` INT NOT NULL,
  `numTurno` INT NOT NULL,
  `DataTurno` DATE NOT NULL,
  INDEX `CodiceDSic_idx` (`CodiceDSic` ASC) VISIBLE,
  INDEX `numTurno_idx` (`numTurno` ASC) VISIBLE,
  INDEX `DataTurno_idx` (`DataTurno` ASC) VISIBLE,
  PRIMARY KEY (`CodiceDSic`, `numTurno`, `DataTurno`),
  CONSTRAINT `CodiceDSic`
    FOREIGN KEY (`CodiceDSic`)
    REFERENCES `FunCampApp`.`ADDETTO SICUREZZA` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numTurno`
    FOREIGN KEY (`numTurno`)
    REFERENCES `FunCampApp`.`TURNO LAVORO` (`NumT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DataTurno`
    FOREIGN KEY (`DataTurno`)
    REFERENCES `FunCampApp`.`TURNO LAVORO` (`DataT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ASSEGNAZIONE A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ASSEGNAZIONE A` (
  `CodiceDSic` INT NOT NULL,
  `CodiceAttrazione` INT NOT NULL,
  INDEX `CodiceAttrazione_idx` (`CodiceAttrazione` ASC) VISIBLE,
  INDEX `COdiceDSic_idx` (`CodiceDSic` ASC) INVISIBLE,
  PRIMARY KEY (`CodiceDSic`, `CodiceAttrazione`),
  CONSTRAINT `CodiceDSic`
    FOREIGN KEY (`CodiceDSic`)
    REFERENCES `FunCampApp`.`ADDETTO SICUREZZA` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodiceAttrazione`
    FOREIGN KEY (`CodiceAttrazione`)
    REFERENCES `FunCampApp`.`ATTRAZIONE` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ADDESTRATORE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ADDESTRATORE` (
  `CF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`FIRMA DR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`FIRMA DR` (
  `IDContratto` INT NOT NULL,
  `CodiceDRec` INT NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `CodiceDRec_idx` (`CodiceDRec` ASC) VISIBLE,
  PRIMARY KEY (`IDContratto`, `CodiceDRec`),
  CONSTRAINT `IDContratto`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodiceDRec`
    FOREIGN KEY (`CodiceDRec`)
    REFERENCES `FunCampApp`.`ADDETTO RECEPTION` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`FIRMA DS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`FIRMA DS` (
  `IDContratto` INT NOT NULL,
  `CodiceDSic` INT NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `CodiceDSic_idx` (`CodiceDSic` ASC) VISIBLE,
  PRIMARY KEY (`IDContratto`, `CodiceDSic`),
  CONSTRAINT `IDCon`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodiceDSic`
    FOREIGN KEY (`CodiceDSic`)
    REFERENCES `FunCampApp`.`ADDETTO SICUREZZA` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`FIRMA DI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`FIRMA DI` (
  `IDContratto` INT NOT NULL,
  `CodiceDI` INT NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `CodiceDI_idx` (`CodiceDI` ASC) VISIBLE,
  PRIMARY KEY (`IDContratto`, `CodiceDI`),
  CONSTRAINT `IDContr`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodiceDI`
    FOREIGN KEY (`CodiceDI`)
    REFERENCES `FunCampApp`.`INSERVIENTE` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`FIRMA A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`FIRMA A` (
  `IDContratto` INT NOT NULL,
  `CFAddestratore` VARCHAR(45) NOT NULL,
  INDEX `IDContratto_idx` (`IDContratto` ASC) VISIBLE,
  INDEX `CFAddestratore_idx` (`CFAddestratore` ASC) VISIBLE,
  PRIMARY KEY (`CFAddestratore`, `IDContratto`),
  CONSTRAINT `IDCont`
    FOREIGN KEY (`IDContratto`)
    REFERENCES `FunCampApp`.`CONTRATTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CFAddestratore`
    FOREIGN KEY (`CFAddestratore`)
    REFERENCES `FunCampApp`.`ADDESTRATORE` (`CF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`RIFERIMENTO P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`RIFERIMENTO P` (
  `codiceT` INT NOT NULL,
  `idP` INT NOT NULL,
  INDEX `codiceT_idx` (`codiceT` ASC) VISIBLE,
  INDEX `idP_idx` (`idP` ASC) VISIBLE,
  PRIMARY KEY (`codiceT`, `idP`),
  CONSTRAINT `codiceTra`
    FOREIGN KEY (`codiceT`)
    REFERENCES `FunCampApp`.`TRANSAZIONE` (`codiceT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idP`
    FOREIGN KEY (`idP`)
    REFERENCES `FunCampApp`.`PACCHETTO OFFERTA` (`idP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`RIFERIMENTO E`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`RIFERIMENTO E` (
  `codiceT` INT NOT NULL,
  `NomeEvento` VARCHAR(45) NOT NULL,
  `DataEvento` DATE NOT NULL,
  INDEX `codiceT_idx` (`codiceT` ASC) VISIBLE,
  INDEX `NomeEvento_idx` (`NomeEvento` ASC) VISIBLE,
  INDEX `DataEvento_idx` (`DataEvento` ASC) VISIBLE,
  PRIMARY KEY (`codiceT`, `NomeEvento`, `DataEvento`),
  CONSTRAINT `codiceTr`
    FOREIGN KEY (`codiceT`)
    REFERENCES `FunCampApp`.`TRANSAZIONE` (`codiceT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NomeEvento`
    FOREIGN KEY (`NomeEvento`)
    REFERENCES `FunCampApp`.`EVENTO SPECIALE` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DataEvento`
    FOREIGN KEY (`DataEvento`)
    REFERENCES `FunCampApp`.`EVENTO SPECIALE` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`RIFERIMENTO A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`RIFERIMENTO A` (
  `codiceT` INT NOT NULL,
  `CodiceAttrazione` INT NOT NULL,
  INDEX `codiceT_idx` (`codiceT` ASC) VISIBLE,
  INDEX `CodiceAttrazione_idx` (`CodiceAttrazione` ASC) VISIBLE,
  PRIMARY KEY (`codiceT`, `CodiceAttrazione`),
  CONSTRAINT `codiceT`
    FOREIGN KEY (`codiceT`)
    REFERENCES `FunCampApp`.`TRANSAZIONE` (`codiceT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodiceAttrazione`
    FOREIGN KEY (`CodiceAttrazione`)
    REFERENCES `FunCampApp`.`ATTRAZIONE` (`Codice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ACQUISTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ACQUISTO` (
  `numEntrata` INT NOT NULL,
  `codiceT` INT NOT NULL,
  INDEX `numEntrata_idx` (`numEntrata` ASC) VISIBLE,
  INDEX `codiceT_idx` (`codiceT` ASC) VISIBLE,
  PRIMARY KEY (`numEntrata`, `codiceT`),
  CONSTRAINT `numEntrata`
    FOREIGN KEY (`numEntrata`)
    REFERENCES `FunCampApp`.`CLIENTE` (`numEntrata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codiceT`
    FOREIGN KEY (`codiceT`)
    REFERENCES `FunCampApp`.`TRANSAZIONE` (`codiceT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`NUTRIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`NUTRIMENTO` (
  `CodiceDI` INT NOT NULL,
  `NomeAnimale` VARCHAR(45) NOT NULL,
  `SpecieAnimale` VARCHAR(45) NOT NULL,
  `Cibo` VARCHAR(45) NOT NULL,
  INDEX `CodiceDI_idx` (`CodiceDI` ASC) VISIBLE,
  INDEX `NomeAnimale_idx` (`NomeAnimale` ASC) VISIBLE,
  INDEX `SpecieAnimale_idx` (`SpecieAnimale` ASC) VISIBLE,
  PRIMARY KEY (`CodiceDI`, `NomeAnimale`, `SpecieAnimale`),
  CONSTRAINT `CodiceDI`
    FOREIGN KEY (`CodiceDI`)
    REFERENCES `FunCampApp`.`INSERVIENTE` (`CodiceD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NomeAnimale`
    FOREIGN KEY (`NomeAnimale`)
    REFERENCES `FunCampApp`.`ANIMALE` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SpecieAnimale`
    FOREIGN KEY (`SpecieAnimale`)
    REFERENCES `FunCampApp`.`ANIMALE` (`specie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`ADDESTRAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`ADDESTRAMENTO` (
  `CodiceAddestratore` VARCHAR(45) NOT NULL,
  `NomeAnimale` VARCHAR(45) NOT NULL,
  `SpecieAnimale` VARCHAR(45) NOT NULL,
  INDEX `CodiceAddestratore_idx` (`CodiceAddestratore` ASC) VISIBLE,
  INDEX `NomeAnimale_idx` (`NomeAnimale` ASC) VISIBLE,
  INDEX `SpecieAnimale_idx` (`SpecieAnimale` ASC) VISIBLE,
  PRIMARY KEY (`CodiceAddestratore`, `NomeAnimale`, `SpecieAnimale`),
  CONSTRAINT `CodiceAddestratore`
    FOREIGN KEY (`CodiceAddestratore`)
    REFERENCES `FunCampApp`.`ADDESTRATORE` (`CF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NomeAnimale`
    FOREIGN KEY (`NomeAnimale`)
    REFERENCES `FunCampApp`.`ANIMALE` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SpecieAnimale`
    FOREIGN KEY (`SpecieAnimale`)
    REFERENCES `FunCampApp`.`ANIMALE` (`specie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FunCampApp`.`PARTECIPAZIONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FunCampApp`.`PARTECIPAZIONE` (
  `numEntrata` INT NOT NULL,
  `NomeEvento` VARCHAR(45) NOT NULL,
  `DataEvento` DATE NOT NULL,
  INDEX `numeEntrata_idx` (`numEntrata` ASC) VISIBLE,
  INDEX `NomeEvento_idx` (`NomeEvento` ASC) VISIBLE,
  INDEX `DataEvento_idx` (`DataEvento` ASC) VISIBLE,
  PRIMARY KEY (`numEntrata`, `NomeEvento`, `DataEvento`),
  CONSTRAINT `numeEntrata`
    FOREIGN KEY (`numEntrata`)
    REFERENCES `FunCampApp`.`CLIENTE` (`numEntrata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NomeEvento`
    FOREIGN KEY (`NomeEvento`)
    REFERENCES `FunCampApp`.`EVENTO SPECIALE` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DataEvento`
    FOREIGN KEY (`DataEvento`)
    REFERENCES `FunCampApp`.`EVENTO SPECIALE` (`data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
